#Some jobs to automate project boards

name: Auto Assign Issues to Projects from their Lables

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign `Priority - Critical` issues
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'Priority - Critical') ||
        contains(github.event.pull_request.labels.*.name, 'Priority - Critical')
      with:
        project: 'https://github.com/jcr7467/UCLAbookstack/projects/4'

    - name: Assign `Priority - High` issues
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'Priority - High') ||
        contains(github.event.pull_request.labels.*.name, 'Priority - High')
      with:
        project: 'https://github.com/jcr7467/UCLAbookstack/projects/5'

    - name: Assign `Priority - Medium` issues
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'Priority - Medium') ||
        contains(github.event.pull_request.labels.*.name, 'Priority - Medium')
      with:
        project: 'https://github.com/jcr7467/UCLAbookstack/projects/6'

    - name: Assign `Priority - Low` issues
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'Priority - Low') ||
        contains(github.event.pull_request.labels.*.name, 'Priority - Low')
      with:
        project: 'https://github.com/jcr7467/UCLAbookstack/projects/7'
